.THEME_NAME {
  .gp-input {

    color: #{'PRIMARY-COLOR'};
    text-shadow: 0 0 0 #{'BACKGROUND-CONTRAST'};
    
    &:focus {
      outline: none;
    }

    &::-webkit-input-placeholder {
      color: rgba(#000, .54);
    }

    &.md-input-invalid {
      color: #{'BACKGROUND-CONTRAST-0.38'};
    }

    &.md-input-disabled{
      color: #{'BACKGROUND-CONTRAST-0.38'};
    }

    &.md-input-focused{
      color: #{'BACKGROUND-CONTRAST-0.54'};
    }
  }
}

